# Generated by Django 5.1.7 on 2025-08-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_booking_quotebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_time_based', models.BooleanField(default=False)),
                ('time_minutes', models.IntegerField(default=0, help_text='Time in minutes if time-based')),
                ('icon', models.CharField(blank=True, help_text='CSS class or icon identifier', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.CharField(choices=[('studio_500', 'Studio (<500 Sq Ft)'), ('studio_1000', 'Studio (500-1000 Sq Ft)'), ('1_bedroom', '1 Bedroom'), ('2_bedrooms', '2 Bedrooms'), ('3_bedrooms', '3 Bedrooms'), ('4_bedrooms', '4 Bedrooms'), ('5_plus_bedrooms', '5+ Bedrooms')], max_length=50)),
                ('bathrooms', models.CharField(choices=[('1_bathroom', '1 Bathroom'), ('2_bathrooms', '2 Bathrooms'), ('3_bathrooms', '3 Bathrooms'), ('4_plus_bathrooms', '4+ Bathrooms')], max_length=50)),
                ('cleaning_type', models.CharField(choices=[('standard', 'Standard Cleaning'), ('deep', 'Deep Cleaning')], max_length=50)),
                ('has_pets', models.CharField(choices=[('no_pets', 'No Pets'), ('has_pets', 'Yes, I have pets')], max_length=50)),
                ('additional_details', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One time'), ('weekly', 'Weekly - 15% Off'), ('bi_weekly', 'Bi Weekly - 10% Off'), ('monthly', 'Monthly - 5% Off')], default='one_time', max_length=20)),
                ('date_of_service', models.DateField()),
                ('time_slot', models.TimeField()),
                ('timezone_choice', models.CharField(choices=[('company', "Our Company's"), ('user', 'Yours')], default='user', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_country_code', models.CharField(default='+1', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('access_method', models.CharField(choices=[('at_home', "I'll be at home"), ('key_under_mat', 'Key under mat'), ('doorman', 'Doorman'), ('lockbox', 'Lockbox'), ('other', 'Other')], default='at_home', max_length=50)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('unit_apt_suite', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('extra_services_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('extra_services', models.ManyToManyField(blank=True, to='bookings.extraservice')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.servicetype')),
            ],
            options={
                'unique_together': {('service_type', 'day_of_week', 'start_time')},
            },
        ),
        migrations.DeleteModel(
            name='QuoteBooking',
        ),
    ]
