# Generated by Django 5.1.7 on 2025-08-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_extraservice_servicetype_booking_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('retail', 'Retail'), ('medical', 'Medical'), ('school', 'School'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='crew_size_hours',
            field=models.CharField(blank=True, choices=[('1_cleaner_2_hours_500', '1 Cleaner Total 2 Hours (<500 Sq Ft)'), ('1_cleaner_3_hours_1000', '1 Cleaner Total 3 Hours (500-1000 Sq Ft)'), ('1_cleaner_4_hours_1500', '1 Cleaner Total 4 Hours (1000-1500 Sq Ft)'), ('2_cleaners_3_hours_2000', '2 Cleaners Total 3 Hours (1500-2000 Sq Ft)'), ('2_cleaners_4_hours_2500', '2 Cleaners Total 4 Hours (2000-2500 Sq Ft)'), ('2_cleaners_5_hours_3000', '2 Cleaners Total 5 Hours (2500-3000 Sq Ft)'), ('3_cleaners_4_hours_4000', '3 Cleaners Total 4 Hours (3000-4000 Sq Ft)'), ('3_cleaners_5_hours_5000', '3 Cleaners Total 5 Hours (4000-5000 Sq Ft)'), ('custom', 'Custom - Contact for Quote')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_conference_rooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_kitchen_areas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_private_offices',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_restrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('1_bathroom', '1 Bathroom'), ('2_bathrooms', '2 Bathrooms'), ('3_bathrooms', '3 Bathrooms'), ('4_plus_bathrooms', '4+ Bathrooms')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('studio_500', 'Studio (<500 Sq Ft)'), ('studio_1000', 'Studio (500-1000 Sq Ft)'), ('1_bedroom', '1 Bedroom'), ('2_bedrooms', '2 Bedrooms'), ('3_bedrooms', '3 Bedrooms'), ('4_bedrooms', '4 Bedrooms'), ('5_plus_bedrooms', '5+ Bedrooms')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cleaning_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Cleaning'), ('deep', 'Deep Cleaning')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='has_pets',
            field=models.CharField(blank=True, choices=[('no_pets', 'No Pets'), ('has_pets', 'Yes, I have pets')], max_length=50, null=True),
        ),
    ]
