# Generated by Django 5.1.7 on 2025-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_quote_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='last_admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
