# Generated by Django 5.1.7 on 2025-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_last_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approval_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
