# Generated by Django 5.1.7 on 2025-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_quote_square_feet_quote_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SquareFeetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('estimated_sqft', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='home_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='num_bathrooms',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='num_bedrooms',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='square_feet_range',
        ),
        migrations.AlterField(
            model_name='quote',
            name='city',
            field=models.CharField(blank=True, default='New York', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='state',
            field=models.CharField(blank=True, default='NY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='home_types',
            field=models.ManyToManyField(blank=True, to='quotes.hometype'),
        ),
        migrations.AddField(
            model_name='quote',
            name='square_feet_options',
            field=models.ManyToManyField(blank=True, to='quotes.squarefeetoption'),
        ),
    ]
