# Generated by Django 5.1.7 on 2025-03-31 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_remove_quote_is_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='home_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.hometype'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='square_feet_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.squarefeetoption'),
        ),
    ]
