# Generated by Django 5.1.7 on 2025-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_detail_images/'),
        ),
    ]
