# Generated by Django 5.1.7 on 2025-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_cleaningextra_extra_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometype',
            name='extra_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Additional time in minutes for this home type'),
        ),
    ]
