# Generated by Django 5.1.7 on 2025-04-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0024_alter_quote_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(blank=True, max_length=100, null=True)),
                ('num_cleaners', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_admin_note', models.TextField(blank=True, null=True)),
                ('approval_token', models.CharField(blank=True, max_length=64, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/pdfs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('booked', 'Booked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('hours_requested', models.IntegerField(blank=True, null=True)),
                ('recurrence_pattern', models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='one_time', max_length=20)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='New York', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='NY', max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('extras', models.ManyToManyField(blank=True, to='quotes.cleaningextra')),
                ('home_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.hometype')),
                ('service_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.servicecategory')),
                ('square_feet_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.squarefeetoption')),
            ],
        ),
    ]
