# Generated by Django 5.1.7 on 2025-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0032_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('square_footage', models.CharField(help_text='Estimated square footage', max_length=50)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
