# Generated by Django 5.1.7 on 2025-09-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0039_booking_get_in_booking_parking_booking_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bath_count',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 Bathroom'), (2, '2 Bathrooms'), (3, '3 Bathrooms'), (4, '4 Bathrooms'), (5, '5 Bathrooms'), (6, 'More than 5 Bathrooms')], help_text='Number of bathrooms in the home', null=True),
        ),
    ]
