# Generated by Django 5.1.7 on 2025-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0040_booking_bath_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEventCleaningQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the customer', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the customer', max_length=254)),
                ('phone_number', models.CharField(help_text='Phone number of the customer', max_length=20)),
                ('address', models.TextField(help_text='Address where the post event cleaning is needed')),
                ('event_description', models.TextField(help_text='Detailed description of the event and cleaning requirements')),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('cleaning_date', models.DateField(help_text='Preferred date for cleaning')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday Party'), ('corporate', 'Corporate Event'), ('holiday', 'Holiday Party'), ('graduation', 'Graduation Party'), ('anniversary', 'Anniversary'), ('other', 'Other')], help_text='Type of event', max_length=50)),
                ('venue_size', models.CharField(choices=[('small', 'Small (up to 50 people)'), ('medium', 'Medium (50-150 people)'), ('large', 'Large (150+ people)')], help_text='Size of the venue', max_length=50)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special cleaning requirements or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
            ],
            options={
                'verbose_name': 'Post Event Cleaning Quote',
                'verbose_name_plural': 'Post Event Cleaning Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
