# Generated by Django 5.1.7 on 2025-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0041_posteventcleaningquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hours_requested',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='hours_requested',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
