# Generated by Django 5.1.7 on 2025-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, default='New York', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, default='NY', max_length=50, null=True),
        ),
    ]
