# Generated by Django 5.1.7 on 2025-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='purchaser_name',
            field=models.CharField(default='CleanHandy', max_length=255),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='recipient_name',
            field=models.CharField(default='CleanHandy', max_length=255),
        ),
    ]
