# Generated by Django 5.1.7 on 2025-04-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_giftcard_purchaser_name_giftcard_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='purchaser_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='recipient_name',
            field=models.CharField(max_length=255),
        ),
    ]
