"""
Django settings for cleanhandy project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-b@l@av@rh*6)xlvgfrhu0a+*h9#l9pb&zdebab*+$(mkg)d73w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# For localhost
ALLOWED_HOSTS = ['*']

# For production
#ALLOWED_HOSTS = ['cleanhandy-production.up.railway.app']



SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False") == "True"

# Add this if not present
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'https://cleanhandy-production.up.railway.app',
    'https://thecleanhandy.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000'
]

# CSRF Settings for better compatibility
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF tokens
CSRF_COOKIE_AGE = 31449600  # 1 year in seconds
CSRF_COOKIE_NAME = 'csrftoken'

# Session Settings
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds


# Email Configuration
# Railway blocks SMTP on free/trial/hobby plans, so we use different backends based on environment

# Check if we're on Railway and have SMTP restrictions
IS_RAILWAY = os.getenv("RAILWAY_ENVIRONMENT", "").lower() in ["production", "preview"]
RAILWAY_PLAN = os.getenv("RAILWAY_PLAN", "").lower()

# Email backend configuration based on environment
if IS_RAILWAY and RAILWAY_PLAN in ["free", "trial", "hobby", ""]:
    # Check if Resend API key is available for real email sending
    resend_api_key = os.getenv("RESEND_API_KEY")
    if resend_api_key:
        print("🚀 Railway free plan detected - Using Resend email service")
        print(f"🔑 Resend API Key: {resend_api_key[:10]}...")
        EMAIL_BACKEND = "quotes.email_backends.ResendEmailBackend"
    else:
        print("🚀 Railway free plan detected - Using console email backend (no RESEND_API_KEY found)")
        print("💡 To enable real email delivery, add RESEND_API_KEY to Railway environment variables")
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    # Use SMTP for local development and Railway Pro/Enterprise
    print("🏠 Local development detected - Using SMTP email backend")
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "matyass91@gmail.com")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "weqwmobbdznudgff")

# Use Resend's default domain for email sending
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "support@thecleanhandy.com")

# Email timeout settings to prevent worker timeouts
EMAIL_TIMEOUT = 10  # 10 seconds timeout for SMTP operations
EMAIL_CONNECTION_TIMEOUT = 5  # 5 seconds for connection establishment

# Additional email settings for production reliability
EMAIL_SUBJECT_PREFIX = '[TheCleanHandy] '
EMAIL_USE_LOCALTIME = True


LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'home'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    "quotes",
    "bookings",
    "customers",
    "adminpanel",
    "blog",
    "accounts",
    "giftcards",
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cleanhandy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'quotes' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quotes.context_processors.all_services',
                'quotes.context_processors.contact_info',
                'quotes.context_processors.about_content',
                'quotes.context_processors.newsletter_form',
            ],
        },
    },
]

WSGI_APPLICATION = 'cleanhandy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = ['static/']

# White noise static stuff
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_CURRENCY = 'usd'
