# Generated by Django 5.1.7 on 2025-04-15 13:19

import giftcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usage_limit', models.IntegerField(default=1)),
                ('times_used', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=giftcards.models.generate_giftcard_code, max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
