# Generated by Django 5.1.7 on 2025-08-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('quotes', '0034_booking_business_type_booking_cleaning_frequency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='QuoteBooking',
        ),
    ]
