# Generated by Django 5.1.7 on 2025-03-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='hours_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='num_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
