# Generated by Django 5.1.7 on 2025-03-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='num_bedrooms',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='square_feet',
        ),
    ]
