# Generated by Django 5.1.7 on 2025-03-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_num_bedrooms_remove_quote_square_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
