# Generated by Django 5.1.7 on 2025-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_hometype_squarefeetoption_remove_quote_home_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squarefeetoption',
            name='estimated_sqft',
        ),
        migrations.AddField(
            model_name='squarefeetoption',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
