# Generated by Django 5.1.7 on 2025-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_remove_quote_home_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes/pdfs/'),
        ),
    ]
