# Generated by Django 5.1.7 on 2025-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_service_service_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
