# Generated by Django 5.1.7 on 2025-04-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_hometype_extra_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cleaning_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='num_cleaners',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hometype',
            name='extra_minutes',
            field=models.PositiveIntegerField(default=180, help_text='Additional time in minutes for this home type'),
        ),
    ]
