# Generated by Django 5.1.7 on 2025-04-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('quotes', '0021_quote_cleaning_type_quote_num_cleaners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
        ),
    ]
