# Generated by Django 5.1.7 on 2025-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('booked', 'Booked'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
