# Generated by Django 5.1.7 on 2025-04-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0003_alter_giftcard_purchaser_name_and_more'),
        ('quotes', '0027_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='giftcards.giftcard'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gift_card_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount discounted using gift card.', max_digits=8, null=True),
        ),
    ]
