# Generated by Django 5.1.7 on 2025-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0033_officequote'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('retail', 'Retail'), ('medical', 'Medical'), ('school', 'School'), ('other', 'Other')], help_text='Type of business for office cleaning', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaning_frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi Weekly'), ('monthly', 'Monthly')], default='one_time', help_text='How often the customer wants cleaning service', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='crew_size_hours',
            field=models.CharField(blank=True, help_text='Selected crew size and hours option', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='frequency_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for recurring service', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('google', 'Google Search'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('advertisement', 'Advertisement'), ('yelp', 'Yelp'), ('other', 'Other')], help_text='How the customer heard about the service', max_length=20, null=True),
        ),
    ]
