# Generated by Django 5.1.7 on 2025-08-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0034_booking_business_type_booking_cleaning_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cleaning_frequency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='crew_size_hours',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='frequency_discount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hear_about_us',
        ),
    ]
