# Generated by Django 5.1.7 on 2025-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0035_remove_booking_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('retail', 'Retail'), ('medical', 'Medical'), ('school', 'School'), ('other', 'Other')], default='office', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaning_frequency',
            field=models.CharField(blank=True, choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi Weekly'), ('monthly', 'Monthly')], default='one_time', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='crew_size_hours',
            field=models.CharField(blank=True, help_text='Format: num_cleaners_hours_sqft (e.g., 1_cleaner_2_hours_500)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('google', 'Google Search'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('advertisement', 'Advertisement'), ('yelp', 'Yelp'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
