# Generated by Django 5.1.7 on 2025-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0036_booking_business_type_booking_cleaning_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('office_cleaning', 'Office Cleaning'), ('home_cleaning', 'Home Cleaning'), ('post_renovation', 'Post Renovation Cleaning'), ('construction', 'Construction Cleaning'), ('move_in_out', 'Move In/Out Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('regular_cleaning', 'Regular Cleaning')], max_length=50, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate per cleaner', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about this rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hourly Rate',
                'verbose_name_plural': 'Hourly Rates',
                'ordering': ['service_type'],
            },
        ),
    ]
