# Generated by Django 5.1.7 on 2025-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0037_hourlyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the customer', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the customer', max_length=254)),
                ('phone_number', models.CharField(help_text='Phone number of the customer', max_length=20)),
                ('address', models.TextField(help_text='Address where the handyman work is needed')),
                ('job_description', models.TextField(help_text='Detailed description of the handyman job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
            ],
            options={
                'verbose_name': 'Handyman Quote',
                'verbose_name_plural': 'Handyman Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
