# Generated by Django 5.1.7 on 2025-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0038_handymanquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='get_in',
            field=models.CharField(blank=True, choices=[('at_home', "I'll be at home"), ('doorman', 'The key is with doorman'), ('lockbox', 'Lockbox on premises'), ('call_organize', 'Call to organize'), ('other', 'Other')], help_text='How the cleaning team will gain access to the property', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking',
            field=models.TextField(blank=True, help_text='Parking instructions for the cleaning team', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet',
            field=models.CharField(blank=True, choices=[('cat', 'Cat'), ('dog', 'Dog'), ('both', 'Both'), ('other', 'Other')], help_text='Type of pet in the household', max_length=10, null=True),
        ),
    ]
