# Generated by Django 5.1.7 on 2025-10-18 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0044_alter_paymentsplit_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='business_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('retail', 'Retail'), ('medical', 'Medical'), ('school', 'School'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
