# Generated by Django 5.1.7 on 2025-10-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0045_remove_business_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsplit',
            name='final_payment_link_created_at',
            field=models.DateTimeField(blank=True, help_text='When the payment link was created', null=True),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='final_payment_link_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the payment link expires', null=True),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='final_payment_link_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Link ID for final payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='final_payment_link_url',
            field=models.URLField(blank=True, help_text='Stripe Payment Link URL for final payment', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('booked', 'Booked'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
