# Generated by Django 5.1.7 on 2025-12-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0047_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCleaningQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cleaning_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bath_count', models.CharField(blank=True, max_length=10, null=True)),
                ('num_cleaners', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('hours_requested', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('recurrence_pattern', models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='one_time', max_length=20)),
                ('get_in', models.CharField(blank=True, max_length=50, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('pet', models.CharField(blank=True, max_length=50, null=True)),
                ('cleaning_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='New York', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='NY', max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.hometype')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.service')),
                ('square_feet_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.squarefeetoption')),
            ],
            options={
                'verbose_name': 'Home Cleaning Quote',
                'verbose_name_plural': 'Home Cleaning Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
