# Generated by Django 5.1.7 on 2025-12-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0048_homecleaningquoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecleaningquoterequest',
            name='hours_requested',
        ),
        migrations.RemoveField(
            model_name='homecleaningquoterequest',
            name='num_cleaners',
        ),
        migrations.RemoveField(
            model_name='homecleaningquoterequest',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='homecleaningquoterequest',
            name='square_feet_options',
        ),
    ]
