# Generated by Django 5.1.7 on 2025-12-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0049_remove_homecleaningquoterequest_hours_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecleaningquoterequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Stores admin notes and email history as JSON', null=True),
        ),
    ]
