# Generated by Django 5.1.7 on 2025-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0050_homecleaningquoterequest_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecleaningquoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('email_sent', 'Email Sent'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='officequote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('email_sent', 'Email Sent'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
