# Generated by Django 5.1.7 on 2025-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0051_homecleaningquoterequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(help_text="Name of the variable (e.g., 'Studio', '1 Bathroom', 'Manhattan Parking fee')", max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this price variable is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Variable',
                'verbose_name_plural': 'Price Variables',
                'ordering': ['variable_name'],
            },
        ),
    ]
