# Generated by Django 5.1.7 on 2025-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0052_pricevariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricevariable',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes (optional)', null=True),
        ),
    ]
