# Generated by Django 5.1.7 on 2025-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0053_pricevariable_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate as percentage (e.g., 8.75 for 8.75%)', max_digits=5)),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'NYC Sales Tax')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether tax is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Settings',
                'verbose_name_plural': 'Tax Settings',
            },
        ),
    ]
