# Generated by Django 5.1.7 on 2025-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0054_taxsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Tax rate as percentage (e.g., 8.750 for 8.750%)', max_digits=6),
        ),
    ]
