# Generated by Django 5.1.7 on 2025-12-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0055_alter_taxsettings_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceVariableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Crew/Size/Hours', 'Home type', 'Number of Bathrooms')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Variable Category',
                'verbose_name_plural': 'Price Variable Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricevariable',
            options={'ordering': ['category', 'variable_name'], 'verbose_name': 'Price Variable', 'verbose_name_plural': 'Price Variables'},
        ),
        migrations.AlterField(
            model_name='pricevariable',
            name='variable_name',
            field=models.CharField(help_text="Name of the variable (e.g., 'Studio', '1 Bathroom', 'Manhattan Parking fee')", max_length=200),
        ),
        migrations.AddField(
            model_name='pricevariable',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this price variable', null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.pricevariablecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='pricevariable',
            unique_together={('category', 'variable_name')},
        ),
    ]
