# Generated by Django 5.1.7 on 2025-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0056_pricevariablecategory_alter_pricevariable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecleaningquoterequest',
            name='cleaning_supply',
            field=models.CharField(blank=True, help_text='Whether customer needs cleaning supply (yes/no)', max_length=10, null=True),
        ),
    ]
