# Generated by Django 5.1.7 on 2026-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0057_homecleaningquoterequest_cleaning_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officequote',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
